### ISSUE TITLE
mbtiles type

### ISSUE THREAD

**Issue by an99990** [DonWasyl/flutter_map_mbtiles_provider#2]
HI,
First thank you for this plugin,
could you provide where you downloaded your mbtiles. I have tried your example with my mbtiles,but i keep getting

```
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:52364/tR_KSkRK2tU=/
The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:52364/tR_KSkRK2tU=/
E/FlutterJNI( 4503): Failed to decode image
E/FlutterJNI( 4503): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1862)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1855)
E/FlutterJNI( 4503):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:448)
I/flutter ( 4503): Exception: Invalid image data
E/FlutterJNI( 4503): Failed to decode image
E/FlutterJNI( 4503): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1862)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1855)
E/FlutterJNI( 4503):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:448)
I/flutter ( 4503): Exception: Invalid image data
E/FlutterJNI( 4503): Failed to decode image
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1862)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1855)
E/FlutterJNI( 4503):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:448)
I/flutter ( 4503): Exception: Invalid image data
E/FlutterJNI( 4503): Failed to decode image
E/FlutterJNI( 4503): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1862)
E/FlutterJNI( 4503):    at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1855)
E/FlutterJNI( 4503):    at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:448)
I/flutter ( 4503): Exception: Invalid image data
```

When i tried another mbtiles, i got this error 
```
I/flutter ( 4639): Failed to load tile for coords: Coords(2421, 5262, 13)
I/flutter ( 4639): Failed to load tile for coords: Coords(2422, 5262, 13)
I/flutter ( 4639): Failed to load tile for coords: Coords(2421, 5261, 13)
I/flutter ( 4639): Failed to load tile for coords: Coords(2422, 5261, 13)
I/flutter ( 4639): Failed to load tile for coords: Coords(2421, 5260, 13)
I/flutter ( 4639): Failed to load tile for coords: Coords(2422, 5260, 13)
```
Any help is appreciated !
Thank you

**Comment by 9clg6** [comment]
Do you solved it ?

**Comment by DonWasyl** [comment]
Do you mean .mbtiles file?
I generate the file in QGIS software: https://qgis.org/pl/site/forusers/download.html

**Comment by 9clg6** [comment]
I mean, how do you solved the error Failed to create image decoder with message 'unimplemented'
